<a href="https://colab.research.google.com/github/GirishNaik711/NLP_Play_Generator/blob/main/NLP_and_Play_Generator_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Bag of Words

In [ ]:
vocab = {}
word_encoding = 1

def bag_of_words(text):
  global word_encoding

  words = text.lower().split(" ")
  bag = {}

  for word in words:
    if word in vocab:
      encoding = vocab[word]
    else:
      vocab[word] = word_encoding
      encoding = word_encoding
      word_encoding += 1

    if encoding in bag:
      bag[encoding] += 1
    else:
      bag[encoding] = 1

  return bag

text = "Hi Hi how are you sir Hi ok fine thank you"
bag = bag_of_words(text)

print(bag)
print(vocab)






In [ ]:
from keras.datasets import imdb
#from keras.preprocessing import sequence
import keras
import tensorflow as tf
import os
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
vocab_size = 88584
Maxlen = 250
batch_size = 64

(train_data, train_label), (test_data, test_label) = imdb.load_data(num_words = vocab_size)

In [ ]:
train_data[1]

In [ ]:
train_data = pad_sequences(train_data, Maxlen)
test_data = pad_sequences(test_data, Maxlen)

In [ ]:
train_data[1]

array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     1,   194,
        1153,   194,  8255,    78,   228,     5,     6,  1463,  4369,
        5012,   134,    26,     4,   715,     8,   118,  1634,    14,
         394,    20,    13,   119,   954,   189,   102,     5,   207,
         110,  3103,    21,    14,    69,   188,     8,    30,    23,
           7,     4,   249,   126,    93,     4,   114,     9,  2300,
        1523,     5,   647,     4,   116,     9,    35,  8163,     4,
         229,     9,   340,  1322,     4,   118,     9,     4,   130,
        4901,    19,

In [ ]:
from keras.layers.serialization import activation
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, 32),
    tf.keras.layers.LSTM(32),
    tf.keras.layers.Dense(1, activation = 'sigmoid')
])

In [ ]:
model.compile(optimizer='rmsprop', loss = 'binary_crossentropy', metrics = ['acc'] )

In [ ]:
history = model.fit(train_data, train_label,epochs = 10, validation_split = 0.2)

Epoch 1/10
625/625 [==============================] - 74s 100ms/step - loss: 0.4519 - acc: 0.7835 - val_loss: 0.3104 - val_acc: 0.8728
Epoch 2/10
625/625 [==============================] - 27s 43ms/step - loss: 0.2566 - acc: 0.9017 - val_loss: 0.2982 - val_acc: 0.8756
Epoch 3/10
625/625 [==============================] - 15s 24ms/step - loss: 0.1963 - acc: 0.9295 - val_loss: 0.3308 - val_acc: 0.8826
Epoch 4/10
625/625 [==============================] - 12s 19ms/step - loss: 0.1578 - acc: 0.9436 - val_loss: 0.3370 - val_acc: 0.8844
Epoch 5/10
625/625 [==============================] - 11s 18ms/step - loss: 0.1285 - acc: 0.9566 - val_loss: 0.3334 - val_acc: 0.8738
Epoch 6/10
625/625 [==============================] - 11s 17ms/step - loss: 0.1063 - acc: 0.9646 - val_loss: 0.3617 - val_acc: 0.8626
Epoch 7/10
625/625 [==============================] - 10s 17ms/step - loss: 0.0899 - acc: 0.9712 - val_loss: 0.3746 - val_acc: 0.8704
Epoch 8/10
625/625 [==============================] - 9s 15ms

In [ ]:
results = model.evaluate(test_data, test_label)
print(results)

782/782 [==============================] - 4s 5ms/step - loss: 0.4915 - acc: 0.8631
[0.49154961109161377, 0.8630800247192383]


In [ ]:
word_index = imdb.get_word_index()

def encode(text):
  tokens = keras.preprocessing.text.text_to_word_sequence(text)
  tokens = [word_index[word] if word in word_index else 0 for word in tokens]
  return pad_sequences([tokens], Maxlen)[0]

text = "I loved the movie it was a great one"
encoded = encode(text)
print(encoded)

1641221/1641221 [==============================] - 0s 0us/step
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 

In [ ]:
reverse_word_index = {value: key for (key, value) in word_index.items()}

def decode(integers):
  pad = 0
  text = " "
  for num in integers:
    if num != pad:
      text += reverse_word_index[num] + " "

  return text[:-1]

print(decode(encoded))

 i loved the movie it was a great one


In [ ]:
def predict(text):
  encoded_text = encode(text)
  pred = np.zeros((1,250))
  pred[0] = encoded_text
  prediction =  model.predict(pred)
  return prediction

review = "it was a bad movie i would never want to watch anything like this"
predict(review)


1/1 [==============================] - 1s 582ms/step


array([[0.2569266]], dtype=float32)

In [ ]:
model.save('sentiment_analysis.h5', )

In [ ]:
from keras.preprocessing import sequence
import keras
import tensorflow as tf
import os
import numpy as np

In [ ]:
path_to_file = tf.keras.utils.get_file('shakespeare.txt', 'https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt')

1115394/1115394 [==============================] - 0s 0us/step


In [ ]:
#from google.colab import files
#path_to_file = list(files.upload()keys())[0]

In [ ]:
text = open(path_to_file, 'rb').read().decode(encoding = 'utf-8')
print(f"length of text file {len(text)}")

length of text file 1115394


In [ ]:
print(text[:250])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.



In [ ]:
vocab = sorted(set(text))

char2idx = {u:i for i,u in enumerate(vocab)}
idx2char = np.array(vocab)

def text_to_int(text):
   return np.array([char2idx[c] for c in text])

text_as_int = text_to_int(text)


In [ ]:
print(f"Text: {text[:13]}")
print(f"Encoded Text: {text_to_int(text[:13])}")

Text: First Citizen
Encoded Text: [18 47 56 57 58  1 15 47 58 47 64 43 52]


In [ ]:
def int_to_text(ints):
  try:
    ints = ints.numpy()
  except:
    pass

  return ''.join(idx2char[ints])

In [ ]:
print(int_to_text(text_as_int[:15]))

First Citizen:



In [ ]:
seq_length = 100
examples_per_epoch = len(text) // (seq_length+1)

char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)

In [ ]:
print(len(char_dataset))
print(examples_per_epoch)

1115394
11043


In [ ]:
sequences = char_dataset.batch(seq_length+1, drop_remainder = True)

In [ ]:
print(len(sequences))


11043


In [ ]:
def split_input_target(chunk):
  input_text = chunk[:-1]
  target_text  = chunk[1:]
  return input_text, target_text

dataset = sequences.map(split_input_target)

In [ ]:
print(len(dataset))

11043


In [ ]:
for x,y in dataset.take(1):
  print("\n\nExample\n")
  print("Input")
  print(int_to_text(x))
  print(len(x))
  print("\nOutput\n")
  print(int_to_text(y))




Example

Input
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You
100

Output

irst Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You 


In [ ]:
Batch_Size = 64
Vocab_Size = len(vocab)
Embedding_Dim = 256
RNN_Units = 1024

Buffer_Size = 1000

data = dataset.shuffle(Buffer_Size).batch(Batch_Size, drop_remainder = True)

In [ ]:
print(len(data))

172


In [ ]:
def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
  model = tf.keras.Sequential([
      tf.keras.layers.Embedding(vocab_size, embedding_dim, batch_input_shape = [batch_size, None]),
      tf.keras.layers.LSTM(rnn_units,
                           return_sequences = True,
                           stateful = True,
                           recurrent_initializer='glorot_uniform'),
      tf.keras.layers.Dense(vocab_size)
  ])
  return model

In [ ]:
model = build_model(Vocab_Size, Embedding_Dim, RNN_Units, Batch_Size)
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (64, None, 256)           16640     
                                                                 
 lstm_1 (LSTM)               (64, None, 1024)          5246976   
                                                                 
 dense_1 (Dense)             (64, None, 65)            66625     
                                                                 
Total params: 5,330,241
Trainable params: 5,330,241
Non-trainable params: 0
_________________________________________________________________


In [ ]:
for input_example_batch, target_example_batch in data.take(1):
  example_batch_prediction = model(input_example_batch)
  print(len(input_example_batch))
  print(len(example_batch_prediction))
  print(example_batch_prediction.shape)
  print(example_batch_prediction)

64
64
(64, 100, 65)
tf.Tensor(
[[[ 3.17284465e-03  1.30099093e-03 -3.44438478e-03 ...  7.72366021e-03
   -1.47688086e-04  3.00669088e-03]
  [ 6.65297965e-03  6.53506722e-03 -4.82277857e-04 ...  3.42233689e-03
    2.62461370e-03  5.84033597e-03]
  [ 7.06211897e-03  8.19018763e-03  7.04456354e-04 ...  5.59834344e-03
   -5.26425336e-03  4.52357670e-03]
  ...
  [ 3.77902994e-04  1.29335616e-02 -2.55867746e-03 ...  9.95040312e-03
    1.63778197e-04  3.78046092e-03]
  [-5.03878761e-03  8.33173376e-03 -2.54076091e-03 ...  5.96209802e-03
    4.98775672e-03 -2.94272113e-03]
  [-7.12792296e-03  4.65330994e-03  6.43714191e-03 ...  9.83332843e-03
    6.10634638e-03 -1.27292378e-03]]

 [[ 3.17284465e-03  1.30099093e-03 -3.44438478e-03 ...  7.72366021e-03
   -1.47688086e-04  3.00669088e-03]
  [ 4.85014729e-03  5.25787240e-03 -1.51410431e-03 ...  8.95122439e-03
   -7.47495843e-03  3.02486680e-03]
  [ 2.55734194e-03  9.37867910e-04  1.21709879e-03 ...  6.84218947e-03
   -1.49506405e-02  1.44907914e-03

In [ ]:
pred = example_batch_prediction[0]
print(len(pred))
print(pred.shape)
print(pred)

100
(100, 65)
tf.Tensor(
[[ 0.00317284  0.00130099 -0.00344438 ...  0.00772366 -0.00014769
   0.00300669]
 [ 0.00665298  0.00653507 -0.00048228 ...  0.00342234  0.00262461
   0.00584034]
 [ 0.00706212  0.00819019  0.00070446 ...  0.00559834 -0.00526425
   0.00452358]
 ...
 [ 0.0003779   0.01293356 -0.00255868 ...  0.0099504   0.00016378
   0.00378046]
 [-0.00503879  0.00833173 -0.00254076 ...  0.0059621   0.00498776
  -0.00294272]
 [-0.00712792  0.00465331  0.00643714 ...  0.00983333  0.00610635
  -0.00127292]], shape=(100, 65), dtype=float32)


In [ ]:
time_pred = pred[0]
print(len(time_pred))
print(time_pred.shape)
print(time_pred)

#Remember: 65 is probability of one single character occuring next as in 1/65 characters will occur next

65
(65,)
tf.Tensor(
[ 0.00317284  0.00130099 -0.00344438  0.0043648   0.00709975 -0.0011986
  0.00277791 -0.00276993  0.00071152 -0.00360421 -0.00373357 -0.00434108
 -0.00166894 -0.00143896  0.00264979 -0.00168237 -0.00086114 -0.00024076
 -0.00452772  0.00051395  0.00105031  0.00014852  0.00498376  0.00487435
 -0.00283953 -0.0017005   0.00079449  0.00190257 -0.00142065 -0.00274788
 -0.00167717 -0.0022655   0.00105819  0.00416457 -0.00045712 -0.0017488
  0.00330564 -0.0004128   0.00074943  0.00242985  0.0015478   0.0025154
  0.00577567  0.00192281  0.00478817 -0.00079689 -0.00156775  0.00093844
 -0.0049705  -0.00145226 -0.00279273 -0.00311282 -0.00521598 -0.00311043
 -0.00046661  0.00399549 -0.00672114  0.00099394  0.00416102  0.00736183
  0.00360698  0.00472827  0.00772366 -0.00014769  0.00300669], shape=(65,), dtype=float32)


In [ ]:
# If we want to determine the predicted character we need to sample the output distribution (pick a value based on probabillity)
sampled_indices = tf.random.categorical(pred, num_samples=1)

# now we can reshape that array and convert all the integers to numbers to see the actual characters
sampled_indices = np.reshape(sampled_indices, (1, -1))[0]
predicted_chars = int_to_text(sampled_indices)

print(len(predicted_chars))
predicted_chars  # and this is what the model predicted for training sequence 1

100


"NRvb,HDt$?Riu\nJ$Gwry-sJ,?kiL'TKYytOsIzTuY&Fnxg bkHi3nW.F$VZjgw&\nDs?wphvdCJZmWsXDjbD.VBqdfRJLjk;PVxDZ"

In [ ]:
def loss(labels, logits):
  return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits = True)

In [ ]:
model.compile(optimizer='adam', loss=loss)

In [ ]:
checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, 'ckpt{epoch}')

checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath= checkpoint_prefix,
    save_weights_only=True)

In [ ]:
history = model.fit(data, epochs=70, callbacks=[checkpoint_callback])

Epoch 1/70
172/172 [==============================] - 17s 82ms/step - loss: 2.5988
Epoch 2/70
172/172 [==============================] - 13s 74ms/step - loss: 1.9210
Epoch 3/70
172/172 [==============================] - 12s 72ms/step - loss: 1.6755
Epoch 4/70
172/172 [==============================] - 12s 70ms/step - loss: 1.5317
Epoch 5/70
172/172 [==============================] - 12s 70ms/step - loss: 1.4441
Epoch 6/70
172/172 [==============================] - 12s 71ms/step - loss: 1.3833
Epoch 7/70
172/172 [==============================] - 13s 72ms/step - loss: 1.3366
Epoch 8/70
172/172 [==============================] - 13s 72ms/step - loss: 1.2965
Epoch 9/70
172/172 [==============================] - 13s 72ms/step - loss: 1.2608
Epoch 10/70
172/172 [==============================] - 12s 70ms/step - loss: 1.2263
Epoch 11/70
172/172 [==============================] - 12s 70ms/step - loss: 1.1923
Epoch 12/70
172/172 [==============================] - 12s 70ms/step - loss: 1.1574
E

In [ ]:
model = build_model(Vocab_Size, Embedding_Dim, RNN_Units, batch_size=1)

In [ ]:
model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))
model.build(tf.TensorShape([1, None]))

In [ ]:
#checkpoint_num = 4
#model.load_weights(tf.train.load.checkpoint(""./training_checkpoints/ckpt_" + str(checkpoint_num)""))
#model.build(tf.TensorShape([1, None]))

In [ ]:
def Generate_text(model, start_string):
  num_generate = 800
  input_eval = [char2idx[s] for s in start_string]
  input_eval = tf.expand_dims(input_eval, 0)

  text_generated = []

  temprature = 1.2

  model.reset_states()
  for i in range(num_generate):
    predictions = model(input_eval)

    predictions = tf.squeeze(predictions, 0)

    predictions = predictions / temprature
    predicted_id = tf.random.categorical(predictions, num_samples = 1)[-1,0].numpy()

    text_generated.append(idx2char[predicted_id])

  return (start_string + ''.join(text_generated))


In [ ]:
inp = input("Type a starting string: ")
print(Generate_text(model, inp))